### ISSUE TITLE
[Question] Is there any documentation about xcactivitylog?

### ISSUE THREAD

**Issue by kateinoigakukun** [spotify/XCLogParser#10]
Thanks for great OSS. I'll try to use this.
But if I understand correctly, `xcactivitylog` just has values without key name.
I'm curious about how did you name them? Is there any documentation? or this can be broken after updating Xcode?

**Comment by ecamacho** [comment]
Hi, I gave a talk about that topic at this year's AltConf. The video will be published shortly. In the meantime, I'll put the documentation about the format in the Wiki in the upcoming week.

**Comment by kateinoigakukun** [comment]
Oh i see! I can't wait your awesome video!

**Comment by ecamacho** [comment]
@kateinoigakukun I added a document about it: https://github.com/spotify/XCLogParser/blob/master/docs/Xcactivitylog%20Format.md And the video of the talk is up: https://www.youtube.com/watch?v=QVwOzfJIDCc

**Comment by kateinoigakukun** [comment]
Awesome! Great thanks.
