### ISSUE TITLE
swiftTypeCheckTimes and swiftFunctionTimes only appearing for main application target

### ISSUE THREAD

**Issue by birwin93** [spotify/XCLogParser#100]
Using xclogparser v0.2.18

I've been playing around with using `-Xfrontend -debug-time-expression-type-checking -Xfrontend -debug-time-function-bodies` to analyze what functions and type checkers are slowing down our build times. 

I've noticed that only the source files in the main application target seem to have `swiftTypeCheckTimes` and `swiftFunctionTimes` populated. All the source files in our dynamic frameworks and static libraries don't though. I've confirmed those targets are also built with the correct compiler flags, and that the method/typechecks + durations are in the build logs in xcode.

Any ideas? Thanks!

**Comment by birwin93** [comment]
It does look like the information is also in the output from running `xclogparser dump`

**Comment by ecamacho** [comment]
Hi! do you have an xcactivitylog to reproduce the error? If you can't provide one, can you share the overall structure of your project to try to mimic it?

**Comment by birwin93** [comment]
Thank you for the quick reply!

Unfortunately I can't share our xcactivitylog. But general structure:

- App target (iOS 11 min)
- Internal Dependencies:
       - static libs
       - dynamic frameworks
- External Dependencies:
       - Carthage
       - a few pre-compiled frameworks

Not sure if it matters, but we use XcodeGen as well

Let me know if you need anymore info!

**Comment by birwin93** [comment]
Hmmmm I actually created a sample project to try and get an xcactivitylog with a similar setup and it worked fine. Must be something weird in our setup. May also just be a complexity issue since our repo is pretty large with tons of chained dependencies

**Comment by birwin93** [comment]
I might try to clone XCLogParser and see if I can figure out what's not working. Any hints on where in the codebase to focus on?

**Comment by birwin93** [comment]
Did some more digging.  Turns out being in frameworks was a red herring. Ended up being related to spaces in file paths. Put up a PR here to fix: https://github.com/spotify/XCLogParser/pull/102

**Comment by ecamacho** [comment]
Thank you for the PR!
