### ISSUE TITLE
Read me update for feature for rootoutput to save HTML.

### ISSUE THREAD

**Issue by pradyhk** [spotify/XCLogParser#110]
I see the feature for rootoutput to save HTML reports in specific folder is merged https://github.com/spotify/XCLogParser/pull/105 but I don't see the feature in Read me with an example which I can refer

On trying below command, getting error on using rootOutput.. please suggest

```
 xclogparser parse --file 02E5868D-9B8A-4D9A-BB7D-846287FD9380.xcactivitylog --rootOutput path --reporter html
Unrecognized arguments: --rootOutput, "path"
```

Xclogparser version used : 0.2.19

**Comment by BalestraPatrick** [comment]
https://github.com/spotify/XCLogParser/pull/105 was merged on September 9, instead 0.2.19 was released on September 3, so it doesn't include that change. For now you can use a version at HEAD until we release a new version of XCLogParser.
