### ISSUE TITLE
HTML Report Fails to parse build errors

### ISSUE THREAD

**Issue by danielroach350** [spotify/XCLogParser#113]
## Swift/Xcode Version
swift 5, Xcode 12.0

## Problem
Hi,
I discovered a possible issue when there are no SubSteps as part of the failure.

The scenario:
attempting to archive a build where the provisioning profile is incorrect or not found. This generates a failure before build compilation of any build steps have been performed. The result is a failure in the root log activities. After doing some local testing I found that the activity logs parse the errors and are stored in the root/main document model. The issue presents its self when attempting to [writeTargetFiles](https://github.com/spotify/XCLogParser/blob/a5ae90d94328768fe57f72363d4594a8cd18515d/Sources/XCLogParser/reporter/HtmlReporter.swift#L111) without any subSteps being performed yet.

an empty array of errors has been written to file but the error count has been updated in the UI so that's great but you cannot see any of the errors generated.

I added these lines [here](https://github.com/spotify/XCLogParser/blob/a5ae90d94328768fe57f72363d4594a8cd18515d/Sources/XCLogParser/reporter/HtmlReporter.swift#L148) to correct it but feels off to me.
```
        if let buildErrors = build.errors, buildErrors.count > 0 {
           stepsWithErrors.append(build)
        }
        if let buildWarnings = build.warnings, buildWarnings.count > 0 {
            stepsWithWarnings.append(build)
        }
```

Report before:
<img width="1532" alt="Screen Shot 2020-12-03 at 2 06 30 PM" src="https://user-images.githubusercontent.com/3433238/101094208-e2a4ea00-3570-11eb-9af8-19a31cd18a26.png">

After:
<img width="1527" alt="Screen Shot 2020-12-03 at 2 09 39 PM" src="https://user-images.githubusercontent.com/3433238/101094454-46c7ae00-3571-11eb-8261-203bb333f7b8.png">

I have not done any extensive testing and would really like to get some input on this.
Thanks!

**Comment by ecamacho** [comment]
@danielroach350 Thank you for reporting it. I modified your solution a bit to append the `build` with no substeps. For cases in which we have errors at the build root level and inside some substeps. Can you check it works for your case? https://github.com/spotify/XCLogParser/pull/115

**Comment by danielroach350** [comment]
Thanks @ecamacho pushing it out to CI for testing.

**Comment by danielroach350** [comment]
@ecamacho that looks to have done the trick! Thanks
