### ISSUE TITLE
I get some files with xcodebuild -resultBundlePath but not .xcactivitylog

### ISSUE THREAD

**Issue by cxr0715** [spotify/XCLogParser#114]
# Version
Version 12.0 (12A7209)
# Problem
Run the following command
```shell
xcodebuild build -workspace TestDemoPod.xcworkspace -scheme TestDemoPod -configuration Debug -sdk iphonesimulator14.0 -arch x86_64 -resultBundlePath TeseDemoPod/Result
```
I get these files
<img width="621" alt="企业微信20201210-152435@2x" src="https://user-images.githubusercontent.com/22252693/101734837-dafabd80-3afb-11eb-838a-cee819b83b1a.png">

I can't get .xcactivitylog file with xcodebuild -resultBundlePath command.
What should I do?
THX

**Comment by ecamacho** [comment]
@cxr0715 can you also pass a `derived data path` flag using `--derived_data /path/to/custom/DerivedData`? After doing that, check in that path. Inside the directory `Logs/Build` there should be `xcactivitylog` files.

**Comment by cxr0715** [comment]
THX!
I use this command and find .xcactivitylog file in Logs/Build
```shell
xcodebuild build -workspace TestDemoPod.xcworkspace -scheme TestDemoPod -configuration Debug -sdk iphonesimulator14.0 -arch x86_64 -derivedDataPath TeseDemoPod/Result
```
