### ISSUE TITLE
10.14.4+ Support

### ISSUE THREAD

**Issue by sendtobo** [spotify/XCLogParser#12]
It seems like XCLOgParser doesnt work on any MacOS after 10.14.4. I am getting this error when running the parser

"This copy of libswiftCore.dylib requires an OS version prior to 10.14.4."

**Comment by BalestraPatrick** [comment]
Hey! How and where did you install `XCLogParser`? I am unable to reproduce the issue on macOS 10.14.5.

**Comment by altaibayar** [comment]
@sendtobo Use Xcode11 command line tools. It worked for me

**Comment by BalestraPatrick** [comment]
@sendtobo Where you able to run `XCLogParser` correctly after fixing your environment?
