### ISSUE TITLE
Expose Reporter.makeLogReporter()

### ISSUE THREAD

**Issue by andreH-B** [spotify/XCLogParser#129]
I'm using `XCLogParser` in a command-line tool that filters out some build steps.
I would still like to be able to use the HTML reporter for the edited builds steps but `HtmlReporter` does not have a public initializer.
A quick way to achieve what I want would be to make `Reporter.makeLogReporter()` public. This way all reporters could be initialized if needed

**Comment by ecamacho** [comment]
I make it public, and I also I added public initializers to each Reporter.
