### ISSUE TITLE
Swift Type check times stopped reporting

### ISSUE THREAD

**Issue by ChristopherDrum** [spotify/XCLogParser#132]
I was using 0.2.16 and just saw that I was out of date.
Using 0.2.16 I was seeing Swift Type check times reported in the HTML report.
I updated to 0.2.26 and re-ran the report and see
`Did you compile your project with the flags -Xfrontend -debug-time-expression-type-checking`

Yes, I did compile with those flags. I ran a report with 0.2.16, it looked fine.
Updated to 0.2.26 and ran the report on the exact same project and nothing.
I double-checked, just in case something strange happened, and the flag is absolutely present.

The `debug-time-function-bodies` report is displaying properly.

**Comment by MadsBogeskov** [comment]
Same problem here :(

**Comment by ecamacho** [comment]
Thank you for reporting the issue. It's been fixed in the latest release: 0.2.27
