### ISSUE TITLE
Logs from builds where Static Analysis was used, can not be parsed

### ISSUE THREAD

**Issue by ecamacho** [spotify/XCLogParser#32]
They fail with the message `Failed to parse log: (Error parsing the log: Unexpected className found parsing IDEActivityLogMessage IDEActivityLogAnalyzerResultMessage)`

**Comment by lstomberg** [comment]
I was wondering why I was seeing these!  So glad to know what causes them.

**Comment by ecamacho** [comment]
@lstomberg the issue is fixed in latest master (v 0.1.5)
