### ISSUE TITLE
Unexpected className found parsing DocumentLocation IBDocumentMemberLocation

### ISSUE THREAD

**Issue by joshavant** [spotify/XCLogParser#36]
Hello,

I'm trying to run `xclogparser` after a build and am getting this error:
`Unexpected className found parsing DocumentLocation IBDocumentMemberLocation`

I'm running on Xcode 11.1 (11A1027)

Any thoughts?

**Comment by ecamacho** [comment]
@joshavant Hi, yes we run into bugs like that from time to time. Basically your Log has a serialised class that we haven't reverse engineered. I will try to reproduce it locally, but it will help me if you can share one of those logs. Can you do it?

**Comment by joshavant** [comment]
Unfortunately, I cannot post the log file as it contains sensitive information (filenames and whatnot).

That said, I opened up the `xcactivitylog` file and did some light reverse engineering and it looks like the `IBDocumentMemberLocation` class reference was triggered by the build warning:
`Automatically Adjusts Font requires using a Dynamic Type text style`

I replicated this subview configuration in a new project, also setting `Project Settings > Shared Project Settings > Build System` to `Legacy Build System` (like our main project is configured), and I was able to reproduce the issue.

Here's that sample project: [WarningTest.zip](https://github.com/spotify/XCLogParser/files/3790624/WarningTest.zip)

**Comment by ecamacho** [comment]
@joshavant Thank you for the sample project. I opened a PR to fix the issue https://github.com/spotify/XCLogParser/issues/36
