### ISSUE TITLE
When trying to set `--derived_data`, if there is an error, the error indicates the flag is `--derived-data`

### ISSUE THREAD

**Issue by mobileben** [spotify/XCLogParser#53]
The error is in LogFinder.swift. I can create a PR in a little bit to fix this.

Also as an aside, do you happen to know if, when you use `--derived_data` if you can make it not look for project directories? At least when I use `-derivedDataPath`, it writes the contents of the project (eg. Build, Logs, etc) directly into that directory.

So for example `-derivedDataPath foo` would yield something like:

foo/Build
foo/Logs
etc

I'm having to add an extra directory to `-derivedDataPath` to get it to work with `xclogparser`. I'm working on some else's build system, so I can't arbitrarily change path like that (or would at least need to have discussions about doing it).

**Comment by ecamacho** [comment]
Yes that's right. That's a bug. I'll create a fix for that, since I've been doing the same artificially create an extra directory when shouldn't be needed. Thanks for reporting it, I can also fix the typo in the error in the same PR

**Comment by mobileben** [comment]
Okay, sounds good! Thanks.

**Comment by ecamacho** [comment]
Hi, this issue is fixed in current version 0.2.3.

**Comment by mobileben** [comment]
@ecamacho thanks here too!
