### ISSUE TITLE
`outputPath` and `machineName` are inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by mobileben** [spotify/XCLogParser#63]
I may be possibly doing things that are were not intended.

I had a tool I wrote in python to take the parse JSON from `xclogparser` which converted into data we could use with some of our other tools. I decided to expand on this, but this time to create a Swift command line tool to do this, leveraging the `XCLogParser` library.

I really don't care about the reporter, rather I want to use the `IDEActivityLog` directly. 

In experimenting/getting used to the library code, I bypassed using `CommandHandler` and `Command` and created my own code based on `XCLogParser` source. Currently it looks something like:

```
let logOptions = config.logOptions()
let actionOptions = config.actionOption()

do {
    let logFinder = LogFinder()
    let logURL = try logFinder.findLatestLogWithLogOptions(logOptions)
    let activityLogParser = ActivityParser()
    let activityLog = try activityLogParser.parseActivityLogInURL(logURL, redacted: config.redact)
    // TODO: Revist
    let buildParser = ParserBuildSteps(machineName: nil)
    let buildSteps = try buildParser.parse(activityLog: activityLog)
    // TODO: Revist
    let reporterOutput = ReporterOutputFactory.makeReporterOutput(path: "")
} catch {   
}
```

The line following you see `// TODO: Revisit` is where I did things like `actionOptions.machineName` and `actionOptions.outputPath`.  The real values I am using are `nil` and the empty string, but for code clarity, it is nice to use it as what is probably intended. 

The problem here is that `machineName` and `outputPath` are not public, and hence inaccessible.  `LogOptions` more or less gets cleanly consumed by `findLatestLogWithLogOptions` whereas `ActionOptions` tends to need it's data pulled out.

Obviously going through `Command`/`CommandHandler` works because it's internal to the library. However, to get the raw data, one doesn't have this nicety that I know of.

It would be helpful to either have getters or to mark them as public.

**Comment by mobileben** [comment]
Quick clarification on this. The need for access level matters less for the reporter. I would theorize that anyone consuming `XCLogParser` as a library would either use `activityLog` or `buildSteps` directly and forgo using the reporters. 

I've ended up solely relying on `buildSteps` since it is more easily consumable than `activityLog`

**Comment by ecamacho** [comment]
@mobileben we exposed those fields as public in this PR https://github.com/spotify/XCLogParser/pull/67
