### ISSUE TITLE
online analysis tool which work with XCLogParser?

### ISSUE THREAD

**Issue by kjing** [spotify/XCLogParser#80]
We use CXLogParser.  we want to upload daily reports to an online analysis tool to have historical trend analysis for individual file's build or unit test of each test case? Do you know to use which online analysis tool?

**Comment by ecamacho** [comment]
Hi, we don't have one yet. One thing you can try is to generate the flatJson report (`xclogparser parse --project MyProject --reporter flatJson --output build_report.json`) and ingest it into a Database that supports Json like MongoDB

**Comment by ecamacho** [comment]
Hi @kjing we're working on a tool to do this. Are you still interested in it? We can talk about it

**Comment by kjing** [comment]
Hi Eick,

Thanks to let me know. Yes, I am very interested in it.

Best,
Kai

**Comment by ecamacho** [comment]
You can check our [XCMetrics](https://github.com/spotify/XCMetrics) project that addresses this
