### ISSUE TITLE
 Unexpected className found parsi3ng IDEActivityLogSection DBGConsoleLog

### ISSUE THREAD

**Issue by TuYuWang** [spotify/XCLogParser#9]
<img width="1207" alt="屏幕快照 2019-06-14 下午3 18 37" src="https://user-images.githubusercontent.com/17824022/59490607-b5193c00-8eb7-11e9-8973-3a0ad6edb634.png">

[79D9C1DE-F736-4743-A7C6-B08ED42A1DFE.xcactivitylog.zip](https://github.com/spotify/XCLogParser/files/3289464/79D9C1DE-F736-4743-A7C6-B08ED42A1DFE.xcactivitylog.zip)

**Comment by ecamacho** [comment]
Thank you for reporting the issue. Indeed, we don't currently support the class `DBGConsoleLog` I'll take a look your log to see if we can add support for it. Which version of Xcode are you using?

**Comment by TuYuWang** [comment]
Xcode Version 10.2.1 (10E1001)

**Comment by ecamacho** [comment]
I've added support for that class in https://github.com/spotify/XCLogParser/pull/17 and tested it with the sample log you provided. Can you check it with other logs?

**Comment by TuYuWang** [comment]
thanks, it is work!
