### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by JustinDSN** [spotify/XCLogParser#95]
Hi there 👋 :

I'm curious what the intention is behind the Docker image. Is this so it can be built with Swift Linux, or is this so the tool can actually be ran from a Docker container?

I'm wondering how you use this tool "at Scale" at Spotify? Do your developers install the tool and run on demand, or are you monitoring for XCActivityLog's and uploading them to AWS S3 (or something similar) for processing and archiving in the cloud.

I work on a developer productivity team @Square and have some interest in using this tool to provide insights into local developer experience.

**Comment by ecamacho** [comment]
We just released [XCMetrics](https://github.com/spotify/XCMetrics), our internal tool that we use to collect the metrics from our devs and CI agents.
